name: Notify Telegram on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram message
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
        -d chat_id=${{ secrets.CHAT_ID }} \
        -d text="New Pull Request created: ${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url }}"name: Notify Telegram on PR

